import os
import cv2
import uuid
import math
import logging
import numpy as np
from datetime import datetime
from typing import Optional, Tuple, Dict, List, Any
from src.types import CrossingEvent
from ultralytics import YOLO

logger = logging.getLogger(__name__)

class ObjectTracker:
    # Class-level attribute to support mocking/autospecing
    session_id: Optional[str] = None

    def __init__(self, 
                 model_name: str = "yolov8n.pt", 
                 tripwire_line: Optional[List[Tuple[float, float]]] = None,
                 snapshot_dir: str = "snapshots",
                 dead_zone_width: float = 0.0,
                 tripwire_strict_segment: bool = False,
                 conf: float = 0.25,
                 track_buffer: int = 30,
                 yolo_imgsz: int = 640,
                 yolo_device: Optional[str] = None):
        """
        Object Tracker utilizing YOLOv8/11 and ByteTrack to trace person trajectories and detect line crossing events.
        
        Args:
            model_name: Name of the YOLO model to use (defaults to yolov8n.pt for CPU efficiency)
            tripwire_line: Normalized tripwire line coordinates [(x1, y1), (x2, y2)]
            snapshot_dir: Directory where person crops are saved
            dead_zone_width: Width of the hysteresis dead zone around the tripwire, as a fraction of frame height.
                When set to 0.0, any signed-distance change across the line triggers an event immediately
                (note: this uses distance-based logic, not segment intersection).
            conf: Minimum detection confidence threshold for YOLO person detections (0.0 to 1.0).
            track_buffer: Number of frames to keep lost tracks alive before reassigning a new tracker ID.
        """
        # Disable Ultralytics telemetry and sync settings to prevent periodic network lag
        try:
            from ultralytics import settings
            settings.update({
                "sync": False,
                "clearml": False,
                "comet": False,
                "dvc": False,
                "hub": False,
                "mlflow": False,
                "neptune": False,
                "raytune": False,
                "tensorboard": False,
                "wandb": False
            })
        except Exception as e:
            logger.warning(f"Could not disable YOLO telemetry/sync settings: {e}")

        # Load YOLO model
        self.model = YOLO(model_name)
        
        # Unique session ID for this instantiation
        self.session_id = str(uuid.uuid4())
        
        # Normalized tripwire line segment, e.g. [(0.2, 0.5), (0.8, 0.5)]
        self.tripwire_line = tripwire_line or [(0.2, 0.5), (0.8, 0.5)]
        self.snapshot_dir = snapshot_dir
        self.dead_zone_width = dead_zone_width
        self.tripwire_strict_segment = tripwire_strict_segment
        self.conf = conf
        self.track_buffer = track_buffer
        self.yolo_imgsz = yolo_imgsz
        self.yolo_device = yolo_device
        os.makedirs(self.snapshot_dir, exist_ok=True)
        
        # Generate a custom tracker config with the specified track_buffer
        self._tracker_config_path = self._create_tracker_config(track_buffer, self.snapshot_dir)
        logger.info(f"ObjectTracker initialized: conf={self.conf}, track_buffer={track_buffer}, dead_zone_width={dead_zone_width}")
        
        # Track history: mapping of tracker_id -> list of centroids (x, y)
        self.track_histories: Dict[int, List[Tuple[float, float]]] = {}
        # Track confirmed side state: mapping of tracker_id -> last known confirmed side (+1 or -1 or 0)
        self.track_confirmed_sides: Dict[int, int] = {}
        # Track last seen frame count to implement TTL buffer
        self.track_last_seen: Dict[int, int] = {}
        # Internal frame counter
        self.frame_count: int = 0
        # Expose latest processed bounding boxes for visualization
        self.latest_boxes = None

    @staticmethod
    def _create_tracker_config(track_buffer: int, snapshot_dir: str) -> str:
        """Creates a custom BoT-SORT tracker config YAML with the specified track_buffer.

        The ultralytics tracker API only accepts a YAML file path for tracker
        configuration — there is no way to pass track_buffer as a direct keyword
        argument — so generating a file is unavoidable.
        """
        config_content = f"""\
# Custom BoT-SORT tracker config (auto-generated by ObjectTracker)
tracker_type: botsort
track_high_thresh: 0.25
track_low_thresh: 0.1
new_track_thresh: 0.25
track_buffer: {track_buffer}
match_thresh: 0.8
fuse_score: true
gmc_method: none
proximity_thresh: 0.5
appearance_thresh: 0.8
with_reid: false
"""
        config_path = os.path.join(snapshot_dir, "tracker_config.yaml")
        with open(config_path, "w") as f:
            f.write(config_content)
        logger.debug(f"Custom tracker config written to: {config_path}")
        return config_path

    def _get_point_side(self, A: Tuple[float, float], B: Tuple[float, float], P: Tuple[float, float]) -> int:
        """
        Determines which side of the directed line segment AB point P is on.
        Returns:
            +1: Left/Clockwise side (designated "inside")
            -1: Right/Counterclockwise side (designated "outside")
            0: Collinear
        """
        val = (B[0] - A[0]) * (P[1] - A[1]) - (B[1] - A[1]) * (P[0] - A[0])
        if abs(val) < 1e-9:
            return 0
        return 1 if val > 0 else -1

    def _get_signed_distance(self, A: Tuple[float, float], B: Tuple[float, float],
                             P: Tuple[float, float]) -> float:
        """
        Returns the signed perpendicular distance from point P to the directed line AB.
        Positive = left/inside side (+1), Negative = right/outside side (-1).
        Result is in the same units as A, B, P (pixels when called from process_frame).
        """
        dx = B[0] - A[0]
        dy = B[1] - A[1]
        line_len = math.sqrt(dx * dx + dy * dy)
        if line_len < 1e-9:
            return 0.0
        return (dx * (P[1] - A[1]) - dy * (P[0] - A[0])) / line_len

    def _is_point_in_segment_bounds(self, A: Tuple[float, float], B: Tuple[float, float], P: Tuple[float, float]) -> bool:
        """
        Checks if the projection of point P onto the line defined by AB falls within the line segment AB.
        """
        # Calculate dot product of AB and AP
        dot_product = (P[0] - A[0]) * (B[0] - A[0]) + (P[1] - A[1]) * (B[1] - A[1])
        # Squared length of segment AB
        segment_len_sq = (B[0] - A[0]) ** 2 + (B[1] - A[1]) ** 2
        
        if segment_len_sq < 1e-9:
            return False
            
        # The projection of P onto the line AB is defined by A + t * AB where t = dot_product / segment_len_sq
        t = dot_product / segment_len_sq
        
        # If t is between 0 and 1, the projection falls on the segment
        # We allow a small margin (e.g. -0.1 to 1.1) to account for bounding box width, or strictly 0.0 to 1.0.
        # Let's use -0.1 to 1.1 to be slightly lenient at the doorway edges.
        return -0.1 <= t <= 1.1

    def save_crop(self, frame: np.ndarray, bbox: Tuple[int, int, int, int], tracker_id: int, event_type: str) -> Optional[str]:
        """Saves a high-resolution crop of the person bounding box for future face recognition."""
        try:
            h, w, _ = frame.shape
            x1, y1, x2, y2 = bbox
            # Clip coordinates
            x1, y1 = max(0, x1), max(0, y1)
            x2, y2 = min(w, x2), min(h, y2)
            
            crop = frame[y1:y2, x1:x2]
            if crop.size == 0:
                return None
                
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
            filename = f"{event_type.lower()}_id{tracker_id}_{timestamp}.jpg"
            filepath = os.path.join(self.snapshot_dir, filename)
            cv2.imwrite(filepath, crop)
            return filepath
        except Exception:
            return None

    def process_frame(self, frame: np.ndarray) -> List[CrossingEvent]:
        """
        Runs object tracking on the frame and checks for tripwire crossings.
        
        Returns:
            List of detected crossing events:
            [CrossingEvent(event_type="ENTER"/"LEAVE", tracker_id=id, confidence=conf, snapshot_path=path)]
        """
        self.frame_count += 1
        self.latest_boxes = None
        h, w, _ = frame.shape
        
        # Compute dead zone threshold in pixel space (based on frame height)
        dead_zone_half_px = (self.dead_zone_width * h) / 2.0
        
        # Convert normalized tripwire coordinates to pixel values
        tx1, ty1 = int(self.tripwire_line[0][0] * w), int(self.tripwire_line[0][1] * h)
        tx2, ty2 = int(self.tripwire_line[1][0] * w), int(self.tripwire_line[1][1] * h)
        A = (float(tx1), float(ty1))
        B = (float(tx2), float(ty2))

        # Run tracking. Classes=0 is 'person'.
        # persist=True ensures the tracking state is maintained.
        results = self.model.track(frame, persist=True, classes=[0], verbose=False,
                                    conf=self.conf, tracker=self._tracker_config_path,
                                    imgsz=self.yolo_imgsz, device=self.yolo_device)
        
        events = []
        active_tracker_ids = set()

        if results and len(results) > 0 and results[0].boxes is not None:
            boxes = results[0].boxes
            self.latest_boxes = boxes
            
            # Extract box coordinates, tracker IDs, and confidences
            # boxes.id contains track identifiers if tracker is running
            if boxes.id is not None:
                xyxy = boxes.xyxy.cpu().numpy()
                tracker_ids = boxes.id.cpu().numpy().astype(int)
                confidences = boxes.conf.cpu().numpy()

                for i, tracker_id in enumerate(tracker_ids):
                    active_tracker_ids.add(tracker_id)
                    self.track_last_seen[tracker_id] = self.frame_count
                    x1, y1, x2, y2 = xyxy[i]
                    conf = confidences[i]
                    
                    # Centroid of bounding box to trace trajectory
                    cx = (x1 + x2) / 2.0
                    cy = (y1 + y2) / 2.0
                    curr_point = (cx, cy)
                    
                    # Initialize track history
                    if tracker_id not in self.track_histories:
                        self.track_histories[tracker_id] = []
                        # Calculate initial side of the tripwire
                        initial_side = self._get_point_side(A, B, curr_point)
                        self.track_confirmed_sides[tracker_id] = initial_side
                        side_label = {1: "INSIDE (+1)", -1: "OUTSIDE (-1)", 0: "COLLINEAR (0)"}.get(initial_side, str(initial_side))
                        logger.info(f"New tracker ID {tracker_id} created at ({cx:.1f}, {cy:.1f}), initial side: {side_label}, conf: {conf:.2f}")
                    
                    confirmed_side = self.track_confirmed_sides[tracker_id]
                    signed_dist = self._get_signed_distance(A, B, curr_point)
                    
                    event_type = None
                    
                    # If strict segment mode is enabled, ignore crossings where the person is outside the doorway bounds
                    in_bounds = True
                    if self.tripwire_strict_segment:
                        in_bounds = self._is_point_in_segment_bounds(A, B, curr_point)
                    
                    if in_bounds:
                        # Hysteresis crossing logic:
                        # Centroid must cross to the opposite side and exceed the dead zone boundary.
                        if confirmed_side == -1 and signed_dist > dead_zone_half_px:
                            event_type = "ENTER"
                            self.track_confirmed_sides[tracker_id] = 1
                            logger.info(f"Tracker {tracker_id} crossed tripwire: OUTSIDE -> INSIDE (ENTER), signed_dist: {signed_dist:.1f}, dead_zone_half: {dead_zone_half_px:.1f}")
                        elif confirmed_side == 1 and signed_dist < -dead_zone_half_px:
                            event_type = "LEAVE"
                            self.track_confirmed_sides[tracker_id] = -1
                            logger.info(f"Tracker {tracker_id} crossed tripwire: INSIDE -> OUTSIDE (LEAVE), signed_dist: {signed_dist:.1f}, dead_zone_half: {dead_zone_half_px:.1f}")
                        elif confirmed_side == 0:
                            # If initially collinear, commit to whichever side the centroid moves towards
                            if signed_dist > dead_zone_half_px:
                                self.track_confirmed_sides[tracker_id] = 1
                                logger.info(f"Tracker {tracker_id} resolved from COLLINEAR -> INSIDE (+1), signed_dist: {signed_dist:.1f}")
                            elif signed_dist < -dead_zone_half_px:
                                self.track_confirmed_sides[tracker_id] = -1
                                logger.info(f"Tracker {tracker_id} resolved from COLLINEAR -> OUTSIDE (-1), signed_dist: {signed_dist:.1f}")
                            
                    if event_type:
                        bbox = (int(x1), int(y1), int(x2), int(y2))
                        snapshot_path = self.save_crop(frame, bbox, tracker_id, event_type)
                        events.append(CrossingEvent(
                            event_type=event_type,
                            tracker_id=int(tracker_id),
                            confidence=float(conf),
                            snapshot_path=snapshot_path
                        ))
                                
                    # Append current point to history and limit size to last 10 points
                    self.track_histories[tracker_id].append(curr_point)
                    if len(self.track_histories[tracker_id]) > 10:
                        self.track_histories[tracker_id].pop(0)

        # Cleanup old tracking histories that are no longer active to prevent memory leaks
        # We use a TTL buffer so we only delete tracks that haven't been seen for track_buffer frames.
        dead_ids = []
        for tid in self.track_histories:
            last_seen = self.track_last_seen.get(tid, 0)
            if tid not in active_tracker_ids and (self.frame_count - last_seen) > self.track_buffer:
                dead_ids.append(tid)
                
        for tid in dead_ids:
            last_side = self.track_confirmed_sides.get(tid)
            side_label = {1: "INSIDE", -1: "OUTSIDE", 0: "COLLINEAR"}.get(last_side, str(last_side))
            logger.info(f"Tracker {tid} lost (no longer active for >{self.track_buffer} frames). Last confirmed side: {side_label}. Cleaning up.")
            del self.track_histories[tid]
            if tid in self.track_confirmed_sides:
                del self.track_confirmed_sides[tid]
            if tid in self.track_last_seen:
                del self.track_last_seen[tid]

        return events
